id: weather_api
namespace: tech3.stream

tasks:
  - id: consume_weather
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    docker:
      image: python:slim
    warningOnStdErr: false
    beforeCommands:
      - pip install openmeteo_requests
      - pip install pandas
      - pip install requests_cache
      - pip install retry_requests
      - pip install kestra
    commands:
      - python weather_api/weather_api_stream.py

  - id: log_api
    type: io.kestra.plugin.core.log.Log
    message: "O resultado da soma é: {{ outputs.consume_weather }}"

  - id: feature_selection
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    docker:
      image: python:slim
    warningOnStdErr: false
    beforeCommands:
      - pip install sqlalchemy
      - pip install pandas
      - pip install psycopg2-binary
      - pip install kestra
    commands:
      - python weather_api/feature_creation.py --data {{ outputs.consume_weather["vars"] }} --db_url "postgresql://kestra:k3str4@localhost:5432/tech3"

  - id: predict_weather
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    docker:
      image: python:slim
    warningOnStdErr: false
    beforeCommands:
        - pip install psycopg2-binary
        - pip install sqlalchemy
        - pip install pandas
        - pip install xgboost
        - pip install joblib
    commands:
      - python weather_api/predict.py  "weather_api/model.pkl" {{ outputs.consume_weather["vars"] }}

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/15 * * * *"
